#!/bin/bash
echo "Starting master server"
cd /home/dragonfly/FogNode/master/
npm run dev 192.168.0.101 192.168.0.105

#when run must change cd and addresses appropriately
#first argument is slave node 99 address
#second argument is other slave nodes address
